### ISSUE TITLE
Object load imports minimal attributes

### ISSUE THREAD

**Issue by cunningr** [macvjuhu/fmc_rest_client#6]
When doing a;

```rules = fmc.list(AccessRule(container=policy))```

We expect to get a full list of expanded rules however we only end up with the id, name and possibly metadata if present

```
class NamedResource(BaseReferenceResource):
    def __init__(self, name, id=None):
        super().__init__(id)
        self.name = name

    def json_load(self, json):
        # print('json to load ' + str(json))
        self.id = json['id']
        self.type = json['type']
        self.name = json['name']
        if 'metadata' in json:
            self.metadata = json['metadata']
```

I fixed this with the addition below but maybe there is a better/safer way?

CUNNINGR-M-91EH:fmc_rest_client cunningr$ git diff
diff --git a/fmc_rest_client/core/base_resources.py b/fmc_rest_client/core/base_resources.py
index 38dd3e6..2e99ff1 100644
--- a/fmc_rest_client/core/base_resources.py
+++ b/fmc_rest_client/core/base_resources.py
@@ -134,6 +134,8 @@ class NamedResource(BaseReferenceResource):
         self.name = json['name']
         if 'metadata' in json:
             self.metadata = json['metadata']
+        for key, value in json.items():
+            setattr(self, key, value)

 class ObjectResource(NamedResource):
     def __init__(self, name, id=None):

**Comment by macvjuhu** [comment]
Fixed in 0.5.3
